import pandas as pd

from typing import Dict
from io import StringIO

from .taxon_manager import TaxonManager


def extract_taxon_scores(csv_content: str) -> Dict[int, float]:
    """
    Read a CSV-file that's been produced by the PepGM algorithm, extract all the score values for all taxa and return
    a dictionary mapping each taxon ID onto its associated score.

    Parameters
    ----------
    csv_content: str,
        A CSV-file that has been generated by running the PepGM algorithm.
    """

    # read csv using pandas
    ids = pd.read_csv(StringIO(csv_content), names=["ID", "score", "type"])
    tax_ids = ids.loc[ids["type"] == "taxon"]
    tax_ids = tax_ids.dropna()

    tax_ids.loc[:, "score"] = pd.to_numeric(tax_ids["score"], downcast="float")
    tax_ids = tax_ids.sort_values("score")

    scores = tax_ids["score"].to_list()

    taxon_score_dict = dict()

    name_mapping = TaxonManager.get_names_for_taxa([int(id) for id in tax_ids["ID"]])

    for (idx, tax_id) in enumerate(tax_ids["ID"]):
        taxon_score_dict[name_mapping[int(tax_id)]] = scores[idx]

    return taxon_score_dict

