import { pepgmGraphGeneration, asyncPepgmExecution } from "./py-worker";

/**
 * Start the peptonizer. This function takes in a PSM-file that has been read in earlier (so no file paths here). The
 * PSMS including their intensities are then used as input to the Peptonizer-pipeline. This pipeline will finally
 * return a Map in which NCBI taxon IDs are mapped onto their propabilities (as computed by the Peptonizer).
 *
 * @param psmContent Content of a PSM-file generated by upstream tools (such as MS2Rescore).
 * @return Mapping between NCBI taxon IDs (integer, > 0) and probabilities (float in [0, 1]).
 */
export async function peptonize(psmContent) {
    return pepgmGraphGeneration({ psms: psmContent })
        .then(data => {
            if (data.error) return { error: data.error };
            return asyncPepgmExecution({ graph: data.graph });
        })
        .then(data => {
            if (data.error) return { error: data.error };
            return data.results;
        });
}

